Improve zsh plugin loading perfs

diff --git a/roles/ansible-role-zsh/templates/zshrc.j2 b/roles/ansible-role-zsh/templates/zshrc.j2
--- a/roles/ansible-role-zsh/templates/zshrc.j2
+++ b/roles/ansible-role-zsh/templates/zshrc.j2
@@ -1,102 +1,99 @@
 # Generated by Ansible
 
+
 ## Operating system detection
-if [[ -a /etc/os-release ]]; then source /etc/os-release; fi
-if [[ NAME == "Arch Linux" ]]; then
-  DISTRO=ARCH
-elif [[ $(uname -s) == Darwin ]]; then
-  DISTRO=DARWIN
-elif [[ $(uname -o) == Cygwin ]]; then
-  DISTRO=CYGWIN
+OS_FAMILY=Unknown
+if [[ "$OSTYPE" == "linux-gnu" ]]; then
+  OS_DISTRIBUTION=$(cat /etc/*-release | grep -w NAME | cut -d= -f2 | tr -d '"')
+
+  case "$OS_DISTRIBUTION" in
+  "RedHat" | "Fedora" | "CentOS" | "SLC" | "Amazon")
+      OS_FAMILY=RedHat
+      ;;
+  "Ubuntu" | "Debian" | "Mint" | "SteamOS")
+      OS_FAMILY=Debian
+      ;;
+  esac
+
+elif [[ "$OSTYPE" == "darwin"* ]]; then
+  OS_FAMILY=Darwin
+else
+  # Unknown.
 fi
 
 ## Functions
 
--xdg-config () {
-  test -f ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs && source ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs
-}
-
--xdg-data-home () {
-  echo ${XDG_DATA_HOME-$HOME/.local/share}
-}
-
--antigen-library-filepath () {
-  if [[ $DISTRO == "DARWIN" ]]; then
-    echo "/usr/local/share/antigen/antigen.zsh"
+-zplug-init-path () {
+  if [[ $OS_FAMILY == "Debian" ]]; then
+    echo "/usr/share/zplug"
+  elif [[ $OS_FAMILY == "Darwin" ]]; then
+    echo "/usr/local/opt/zplug"
   else
-    echo "$_ANTIGEN_INSTALL_DIR/antigen.zsh"
+    echo "$HOME/.zplug"
   fi
 }
 
--antigen-load () {
-  if [[ ! -f $(-antigen-library-filepath) ]]; then
-    -antigen-install
+-zplug-load () {
+  if ! zplug check; then
+    zplug install
+  fi
+  # source plugins and add commands to the PATH
+  zplug load
+}
+
+-zplug-failed () {
+  COMMAND_HINT='Try to install it.'
+  if [[ $OS_FAMILY == "Darwin" ]]; then
+    COMMAND_HINT="Try `brew install zplug`"
+  elif [[ $OS_FAMILY == "Debian" ]]; then
+    COMMAND_HINT="Try `sudo apt install zplug`"
+  fi
+  echo "zplug not found. $COMMAND_HINT"
+}
+
+-zsh-load-plugins() {
+  ## Load everything in .zshrc.d/
+  if [[ -d "$_ZSH_PLUGINS/" ]]; then
+    for i in $(find "$_ZSH_PLUGINS/" -maxdepth 1 -type f -name "*.sh");
+    do
+      . $i;
+    done
   fi
 }
 
--antigen-install () {
-  if [[ $DISTRO == "DARWIN" ]]; then
-    echo "antigen not found. Try brew install antigen"
-  else
-    mkdir -p $_ANTIGEN_INSTALL_DIR
-    curl -L git.io/antigen > $_ANTIGEN_INSTALL_DIR/antigen.zsh
-  fi
-}
+## Load ZPlug
+export ZPLUG_HOME=$(-zplug-init-path)
+_ZSH_PLUGINS="$HOME/.zshrc.d"
 
-## Load xdg
--xdg-config
+if [[ -f "$ZPLUG_HOME/init.zsh" ]];then
+  source "$ZPLUG_HOME/init.zsh"
+  # Load theme file
+  zplug 'themes/pygmalion', from:oh-my-zsh, as:theme
+  # Load Plugins
+  zplug "zsh-users/zsh-autosuggestions"
+  zplug "zsh-users/zsh-completions"
+  zplug "zsh-users/zsh-history-substring-search"
+  zplug "zsh-users/zsh-syntax-highlighting"
+  zplug "chrissicool/zsh-256color"
+  zplug "lib/clipboard", from:oh-my-zsh
+  zplug "lib/compfix", from:oh-my-zsh
+  zplug "lib/completion", from:oh-my-zsh
+  zplug "lib/correction", from:oh-my-zsh
+  zplug "lib/grep", from:oh-my-zsh
+  zplug "lib/history", from:oh-my-zsh
+  # zplug "lib/key-bindings", from:oh-my-zsh
+  # zplug "plugins/git", from:oh-my-zsh, if:"(( $+commands[git] ))"
+  # zplug "plugins/osx", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]", defer:3
 
-## Default config
-_ZSH_AUTOLOAD_DIR="$HOME/.zshrc.d"
-_ANTIGEN_INSTALL_DIR="$HOME/.antigen"
-if ! ${XDG_SESSION_ID+"false"}; then
-  _ANTIGEN_INSTALL_DIR=$(-xdg-data-home)/zsh-antigen
-  export ADOTDIR=$_ANTIGEN_INSTALL_DIR/repo
-fi
+  # zplug "$_ZSH_PLUGINS", from:local
 
-## Load / Clone antigen
--antigen-load
-source $(-antigen-library-filepath)
+  -zsh-load-plugins
+  -zplug-load
+else
+  -zplug-failed
+  -zsh-load-plugins
+fi;
 
-## Load Base
-antigen use oh-my-zsh
-antigen theme pygmalion
-
-antigen bundles <<EOF
-  colorize
-  colored-man-page
-  command-not-found
-  cp
-  git
-  chrissicool/zsh-256color
-  zsh-users/zsh-autosuggestions
-  zsh-users/zsh-completions
-  zsh-users/zsh-history-substring-search
-  zsh-users/zsh-syntax-highlighting
-EOF
-
-## Load distro specific plugins
-# Arch Linux plugins
-if [[ $DISTRO == ARCH ]]; then
-  antigen bundle archlinux
-elif [[ $DISTRO == DARWIN ]]; then
-  antigen bundle osx
-fi
-
-## Load from plugins file
-if [[ -f ~/.zsh_plugins.txt ]]; then
-  antigen bundles < ~/.zsh_plugins.txt
-fi
-
-## Load everything in .zshrc.d/
-if [[ -d $_ZSH_AUTOLOAD_DIR/ ]]; then
-  for i in $(find "$_ZSH_AUTOLOAD_DIR/" -maxdepth 1 -type f -name "*.sh");
-  do
-    . $i;
-  done
-fi
-
-antigen apply
 
 # Improve PATH with local/bin
 if [ -d ~/.local/bin/ ]; then
